everywhere:
  type: bool
  default: false
  description: "Show minimal nav all the time (overrides home_page/tag_pages/category_pages settings)"
on_home_page:
  type: bool
  default: false
  description: "Show minimal nav on homepage"
on_tag_pages:
  type: bool
  default: false
  description: "Show minimal nav on tag pages"
on_category_pages:
  type: bool
  default: false
  description: "Show minimal nav on category pages"
dropdown_icon:
  type: string
  default: "caret-right"
rotate_icon_on_open:
  type: integer
  default: 90
