on_home_page:
  type: bool
  default: false
  description: "Show minimal nav on homepage"
on_tag_pages:
  type: bool
  default: false
  description: "Show minimal nav on tag pages"
on_category_pages:
  type: bool
  default: false
  description: "Show minimal nav on category pages"
nav_items_to_exclude:
  type: list
  default: ""
  description: "A list of nav item names to exclude from the 'compact' nav, and keep in the nav pills list. ATTN: It is whatever is used in the `name` property, not to be confused with the `displayName`."